INSERT INTO pokemon (numero, nombre, tipo_principal, tipo_secundario, altura, peso, habilidad, imagen, descripcion) VALUES
(1,   'Bulbasaur', 'Planta',    'Veneno',  0.7, 6.9,   'Espesura',    'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png',   'Puede pasar días sin comer gracias al bulbo de su lomo.'),
(6,   'Charizard', 'Fuego',     'Volador', 1.7, 90.5,  'Mar Llamas',  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png',   'Escupe fuego capaz de fundir rocas y provocar incendios.'),
(7,   'Squirtle',  'Agua',      NULL,      0.5, 9.0,   'Torrente',    'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png',   'Se oculta en su caparazón cuando se siente en peligro.'),
(25,  'Pikachu',   'Eléctrico', NULL,      0.4, 6.0,   'Electricidad Estática', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png', 'Guarda electricidad en sus mejillas y la libera cuando se asusta.'),
(94,  'Gengar',    'Fantasma',  'Veneno',  1.5, 40.5,  'Cuerpo Maldito', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png', 'Se dice que aparece de entre las sombras para robar vidas.'),
(130, 'Gyarados',  'Agua',      'Volador', 6.5, 235.0, 'Intimidación', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/130.png', 'Extremadamente violento, destruye ciudades enteras cuando se enfurece.'),
(133, 'Eevee',     'Normal',    NULL,      0.3, 6.5,   'Fuga',        'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png', 'Su estructura genética inestable le permite evolucionar de muchas formas.'),
(143, 'Snorlax',   'Normal',    NULL,      2.1, 460.0, 'Inmunidad',   'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png', 'Come 400 kg de comida al día y luego se queda profundamente dormido.'),
(149, 'Dragonite', 'Dragón',    'Volador', 2.2, 210.0, 'Foco Interno', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png', 'Puede dar la vuelta al mundo en solo 16 horas volando sobre el mar.'),
(151, 'Mew',       'Psíquico',  NULL,      0.4, 4.0,   'Sincronía',   'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/151.png', 'Posee el código genético de todos los Pokémon, considerado el ancestro de todos.')
ON CONFLICT (numero) DO NOTHING;
